version: '3.5'
services:
    mysqlsrv:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: dbtest
            MYSQL_USER: user
            MYSQL_PASSWORD: 123456
        networks:
            - mysql-compose-network

volumes:
  my-db:

networks:
  mysql-compose-network:
    driver: bridge
